# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
xcode_workspace: TCSCustomRowActionFactory.xcworkspace
xcode_scheme: TCSCustomRowActionFactory-Example
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild -workspace Example/TCSCustomRowActionFactory.xcworkspace -scheme TCSCustomRowActionFactory-Example -destination platform\=iOS\ Simulator,OS\=10.3.1,name\=iPhone\ 7 build test | xcpretty
- pod lib lint --verbose
